# Site settings
title: "SENSE 1.0"
description: "SENSE is an external cheat for Counter-Strike: Global Offensive. At the moment this cheat features 'Glow ESP', 'Skinchanger', 'Chams', 'FOVchanger', 'Bunnyhop' and 'Triggerbot'"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: SENSE


# Build settings
markdown: kramdown
permalink: pretty
